<?php
/*
 * This file is part of the Sulu CMS.
 *
 * (c) bytepark GmbH
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Sulu\Bundle\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventEntryFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package    Sulu\Bundle\EventBundle\DataFixtures\Events
 * @author     bytepark GmbH <code@bytepark.de>
 * @link       http://www.bytepark.de
 */
class EventEntryFeeRepository extends EntityRepository implements EventEntryFeeRepositoryInterface
{
}
